CREATE TABLE IF NOT EXISTS HIT (
                                    hit_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                    app VARCHAR(255) NOT NULL,
                                    uri VARCHAR(512) NOT NULL,
                                    ip VARCHAR(45) NOT NULL,
                                    time VARCHAR(512),
                                    CONSTRAINT UQ_HIT UNIQUE (hit_id)
);