CREATE TABLE IF NOT EXISTS HIT (
                                    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                    app VARCHAR(255) NOT NULL,
                                    uri VARCHAR(512) NOT NULL,
                                    ip VARCHAR(512) NOT NULL,
                                    timestamp VARCHAR(512)
);